apiVersion: v1
kind: Service
metadata:
  name: survey-service
spec:
  selector:
    app: survey
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010  # Ensure the NodePort is accessible
